### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by xiaojidan** [ranjanZ/CVPR2018_Dehazing#1]
Can you share the training codes?

**Comment by ranjanZ** [comment]
Sure.  We will upload the training code after cleaning it.

**Comment by gangruipeng** [comment]
Can you share the paper's name?

**Comment by xiaojidan** [comment]
good. I am waiting

**Comment by ranjanZ** [comment]
@gangruipeng Here is the paper link
 http://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w13/Mondal_Image_Dehazing_by_CVPR_2018_paper.pdf

**Comment by ranjanZ** [comment]
Training code added. Please  change the load_data()  function  in train_model.py to train with your own desired image
