### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by gangruipeng** [ranjanZ/CVPR2018_Dehazing#3]
First, thank you for your answer! And can you tell me where I can download these datasets you refered in your paper,  such as Fattal dataset and NTIRE dehazing dataset?

**Comment by san-santra** [comment]
The dataset of Fattal
[http://www.cs.huji.ac.il/~raananf/projects/dehaze_cl/results/](url)
NTIRE Dataset:
O-Haze: [http://www.meo.etc.upt.ro/AncutiProjectPages/O-Haze/](O-Haze)
I-Haze: [http://www.meo.etc.upt.ro/AncutiProjectPages/I-HAZE/](I-Haze)

**Comment by gangruipeng** [comment]
> The dataset of Fattal
> [http://www.cs.huji.ac.il/~raananf/projects/dehaze_cl/results/](url)
> NTIRE Dataset:
> O-Haze: [http://www.meo.etc.upt.ro/AncutiProjectPages/O-Haze/](O-Haze)
> I-Haze: [http://www.meo.etc.upt.ro/AncutiProjectPages/I-HAZE/](I-Haze)

**Comment by gangruipeng** [comment]
Thanks a lot!
